const CANCIONES = {
    "discos":[
        {
            "artista": "Destruction",
            "artistaId": "destruction",
            "disco": "Thrash Anthems",
            "comment": "Thrash Anthems es un álbum publicado por la banda de Thrash metal Destruction en 2007. El álbum es una compilación de re-grabaciones de canciones antiguas y dos nuevas canciones: Deposition (Your Heads Will Roll) y Profanity.",
            "canciones": [
                "Bestial Invasion",
                "Profanity",
                "Release from Agony",
                "Mad Butcher",
                "Reject Emotions",
                "Death Trap",
                "Cracked Brain",
                "Life Without Sense",
                "Total Desaster",
                "Deposition (Your Heads Will Roll)",
                "Invincible Force",
                "Sign of Fear",
                "Tormentor",
                "Unconscious Ruins",
                "Curse the Gods"
            ],
            "duraciones": [
                "4:38",
                "5:56",
                "4:36",
                "3:45",
                "5:52",
                "4:52",
                "3:46",
                "6:22",
                "3:26",
                "5:11",
                "3:44",
                "6:36",
                "3:55",
                "4:17",
                "5:16"
            ],
            "reproducciones":[
                "100.378",
                "97.534",
                "148.004",
                "191.761",
                "1.162.495",
                "170.052",
                "211.733",
                "114.669",
                "260.015",
                "67.935",
                "85.054",
                "69.678",
                "109.875",
                "61.170",
                "2.502.667"
            ]
            
        },
        {
            "artista": "Arch Enemy",
            "artistaId": "archEnemy",
            "disco": "Burning Angel",
            "comment": "Burning Angel es un EP de la banda sueca Arch Enemy. Publicado el 6 de marzo de 2002, es el segundo álbum de Arch Enemy con Angela Gossow quien tomará el lugar de Johan Liiva en la banda. La canción «Starbreaker» de Judas Priest fue publicada originalmente en el álbum Sin After Sin.",
            "canciones": [
                "Burning Angels",
                "Lament of a Mortal Soul",
                "Starbreaker",
                "Ravenous",
            ],
            "duraciones": [
                "4:38",
                "5:56",
                "4:36",
                "3:45",
            ],
            "reproducciones":[
                "100.378",
                "97.534",
                "148.004",
                "191.761"
            ]
            
        },
        {
            "artista": "Megadeth",
            "artistaId": "megadeth",
            "disco": "Countdown to Extinction",
            "comment": "Countdown to Extinction —en español: Cuenta regresiva hacia la extinción— es el quinto álbum de estudio de la banda estadounidense de thrash metal Megadeth. Fue lanzado al mercado el 14 de julio de 1992. Una versión remasterizada con varias pistas extra fue relanzada en el 2004. Este álbum es considerado uno de los mejores discos de Megadeth, ya que trae consigo varias de las canciones más exitosas del grupo, tales como: Symphony of Destruction, Sweating Bullets, Foreclosure of a Dream, Skin o' My Teeth, entre otras.",
            "canciones": [
                "Skin o' My Teeth",
                "Symphony of Destruction",
                "Architecture of Aggression",
                "Foreclosure of a Dream",
                "Sweating Bullets",
                "This Was My Life",
                "Countdown to Extintion",
                "High Speed Dirt",
                "Psychotron",
                "Captive Honour",
                "Ashes in Your Mouth",
                "Breakpoint",
                "Go to Hell",
                "Crown of Worms",
                "Countdown to Extinction",
                "Symphony of Destruction",
                "Psychotron"
            ],
            "duraciones": [
                "4:38",
                "5:56",
                "4:36",
                "3:45",
                "5:52",
                "4:52",
                "3:46",
                "6:22",
                "3:26",
                "5:11",
                "3:44",
                "6:36",
                "3:55",
                "4:17",
                "5:16",
                "4:52",
                "3:26",
            ],
            "reproducciones":[
                "100.378",
                "97.534",
                "148.004",
                "191.761",
                "1.162.495",
                "170.052",
                "211.733",
                "114.669",
                "260.015",
                "67.935",
                "85.054",
                "69.678",
                "109.875",
                "61.170",
                "502.667",
                "5.102.667",
                "2.667",
            ]
            
        },
        {
            "artista": "Flema",
            "artistaId": "flema",
            "disco": "Si el placer es un pecado... bienvenidos al infierno",
            "comment": "Si el placer es un pecado… bienvenidos al Infierno, es el tercer álbum de estudio de la banda de punk rock argentina Flema, editado en el año 1997. Es citado como uno de sus mejores trabajos. Fue remasterizado en 2002 con 6 Bonus track y reeditado por Ying Yang Records años más tarde, sin los Bonus tracks.",
            "canciones": [
                "Intro",
                "Lección de hipocresía",
                "La canción de Adán y Eva",
                "Quizás",
                "Vagos del ayer",
                "Me echaron de casa",
                "Ahogado en alcohol",
                "Mejor quemarse",
                "Anarquía en la escuela",
                "Bienvenido el vino",
                "Nunca seré policía",
                "Sólo me ves fumar",
                "Pobre Luis",
                "Fist fucking",
                "El último vaso de vino",
                "No te vayas",
                "A nadie",
                "En la nada",
                "Luzbel"
            ],
            "duraciones": [
                "4:38",
                "5:56",
                "4:36",
                "3:45",
                "5:52",
                "4:52",
                "3:46",
                "6:22",
                "3:26",
                "5:11",
                "3:44",
                "6:36",
                "3:55",
                "4:17",
                "5:16",
                "5:16",
                "5:16",
                "5:16",
                "5:16",
            ],
            "reproducciones":[
                "100.378",
                "97.534",
                "148.004",
                "191.761",
                "1.162.495",
                "170.052",
                "211.733",
                "114.669",
                "260.015",
                "67.935",
                "85.054",
                "69.678",
                "109.875",
                "61.170",
                "2.502.667",
                "2.502.667",
                "2.502.667",
                "2.502.667",
                "2.502.667",
            ]
            
        },
        {
            "artista": "Hermetica",
            "artistaId": "hermetica",
            "disco": "Acido Argentino",
            "comment": "Ácido argentino es el segundo álbum de estudio de la banda argentina de thrash metal Hermética, publicado en 1991 por el sello discográfico Radio Trípoli Discos.Es el primer álbum de la banda con el baterista Claudio Strunz. El disco contó con una mejor producción que el primero de la banda, Hermética. Posee en general un ritmo más rápido que este, sin embargo las letras del álbum abordan temáticas como los nativos argentinos, las diferencias sociales y la contaminación, similares al primer trabajo. Ácido argentino logró ser certificado como disco de oro.",
            "canciones": [
                "Robó un auto",
                "La revancha de América",
                "Memoria de siglos",
                "Predicción",
                "Atravesando todo límite",
                "horizonte perdido",
                "Vientos de poder",
                "Del camionero",
                "Gil trabajador",
                "Evitando el ablande",
                "En las calles de Liniers",
                "De pismanta a bauchaceta"
            ],
            "duraciones": [
                "4:38",
                "5:56",
                "4:36",
                "3:45",
                "5:52",
                "4:52",
                "3:46",
                "6:22",
                "3:26",
                "5:11",
                "3:44",
                "6:36"
            ],
            "reproducciones":[
                "100.378",
                "97.534",
                "148.004",
                "191.761",
                "1.162.495",
                "170.052",
                "211.733",
                "114.669",
                "260.015",
                "67.935",
                "85.054",
                "69.678"
            ]
            
        },
        {
            "artista": "Horcas",
            "artistaId": "horcas",
            "disco": "Reviviendo Huestes",
            "comment": "Reviviendo Huestes es el octavo álbum de estudio de la banda argentina de heavy metal Horcas, publicado en 2008 por Tocka Discos/Sony BMG. Musicalmente, el álbum continúa con la línea de sus predecesores, Demencial y Asesino, siendo un disco orientado hacia el metal moderno, y siguiendo con la experimentación con afinaciones bajas, esta vez pasando de Do# a Do.",
            "canciones": [
                "Nacer morir ",
                "Existir por existir",
                "Familia",
                "Pegar y gozar",
                "Infierno",
                "La cruz",
                "Respeto",
                "Crimanales de memoria",
                "Fuego sin Luz",
                "Sin lágrimas",
                "Persistir",
                "Solución suicida"
            ],
            "duraciones": [
                "4:38",
                "5:56",
                "4:36",
                "3:45",
                "5:52",
                "4:52",
                "3:46",
                "6:22",
                "3:26",
                "5:11",
                "3:44",
                "6:36"
            ],
            "reproducciones":[
                "100.378",
                "97.534",
                "148.004",
                "191.761",
                "1.162.495",
                "170.052",
                "211.733",
                "114.669",
                "260.015",
                "67.935",
                "85.054",
                "69.678"
            ]
            
        },
        {
            "artista": "Rancid",
            "artistaId": "rancid",
            "disco": "...And out come the wolves",
            "comment": "...And Out Come the Wolves es el tercer álbum de estudio de la banda de punk Rancid, publicado en agosto de 1995. El culto a la popularidad de Rancid y sus pegadizas canciones, los hizo objeto de una importante guerra entre las discográficas (de ahí el título, ...And Out Come the Wolves), que terminó con el grupo firmando en la discográfica independiente, Epitaph Records. Con un sonido muy influido por el ska, Rancid se convirtió en una de las pocas bandas de mediados y fines de los años 1990 en conservar gran parte de sus primeros fanes.",
            "canciones": [
                "Maxwell Murder",
                "The 11th Hour",
                "Roots Radicals",
                "Time Bomb",
                "Olympia, WA.",
                "Lock, Step & Gone",
                "Junkie Man",
                "Listed M.I.A.",
                "Ruby Soho",
                "Daly City Train",
                "Journey to the End of the East Bay",
                "She's Automatic",
                "Old Friend",
                "Disorder and Disarray",
                "The Wars End",
                "You Don't Care Nothin'",
                "As Wicked",
                "Avenues & Alleyways",
                "The Way I Feel"
            ],
            "duraciones": [
                "4:38",
                "5:56",
                "4:36",
                "3:45",
                "5:52",
                "4:52",
                "3:46",
                "6:22",
                "3:26",
                "5:11",
                "3:44",
                "6:36",
                "3:55",
                "4:17",
                "5:16",
                "5:16",
                "5:16",
                "5:16",
                "5:16",
            ],
            "reproducciones":[
                "100.378",
                "97.534",
                "148.004",
                "191.761",
                "1.162.495",
                "170.052",
                "211.733",
                "114.669",
                "260.015",
                "67.935",
                "85.054",
                "69.678",
                "109.875",
                "61.170",
                "2.502.667",
                "2.502.667",
                "2.502.667",
                "2.502.667",
                "2.502.667",
            ]
            
        },
        {
            "artista": "Kataklysm",
            "artistaId": "katalysm",
            "disco": "Meditations",
            "comment": "Kataklysm es una banda canadiense de death metal, fundada en 1991 en la ciudad de Montreal, Quebec. Ellos llaman a su estilo musical como \"northern hyperblast\" (\"hiperexplosión norteña\") después de un anuncio publicado en la revista M.E.A.T. describiendo a otra banda, Fear Factory, como \"hyperblast\". El término refiere a la extrema rapidez y energía en la percusión mostrada por su baterista, Max Duhamel, tanto en el estudio como en los shows en vivo.",
            "canciones": [
                "Guillotine",
                "Outsider",
                "The Last Breath I'll Take Is Yours",
                "Narcissist",
                "Born To Kill And Destined To Die",
                "In Limbic Resonance",
                "And Then I Saw Blood",
                "What Doesn't Break Doesn't Heal",
                "Bend The Arc, Cut The Cord",
                "Achilles Heel"
            ],
            "duraciones": [
                "2:56",
                "3:57",
                "3:14",
                "2:41",
                "3:57",
                "4:51",
                "4:37",
                "3:21",
                "3:48",
                "5:19"
            ],
            "reproducciones":[
                "100.378",
                "97.534",
                "148.004",
                "191.761",
                "1.162.495",
                "170.052",
                "211.733",
                "114.669",
                "260.015",
                "67.935"
            ]
            
        },
        {
            "artista": "Motörhead",
            "artistaId": "motorhead",
            "disco": "Everything Louder Forever",
            "comment": "Una colección perfecta de Motörhead para fans nuevos o viejos. A diferencia de muchas colecciones de grandes éxitos oficiales y no oficiales, esta no se centra solo en los primeros álbumes con la alineación clásica original de Lemmy Kilmister, Philthy Animal Taylor y Fast Eddie Clark. No, esta colección celebra cada época de Motorhead. Tanto es así que la nota de línea enumera a todos los que pasaron tiempo como miembros oficiales. Golpes, cortes profundos y un par de sorpresas. Recomiendo encarecidamente esta colección.",
            "canciones": [
                "Kill by death",
                "Stay out of jail",
                "Iron Fist",
                "Shine",
                "Overnight sensation",
                "Sacrifice",
                "Bomber",
                "No class",
                "Overkill",
                "In the name of tragedy",
                "We are Mötorhead",
                "Orgasmatron",
                "Ace of spades (40th anniversay)",
                "The chase is better than the catch",
                "God save the queen",
                "Rock out",
                "Dirty love",
                "Stone dead forever"
            ],
            "duraciones": [
                "4:38",
                "5:56",
                "4:36",
                "3:45",
                "5:52",
                "4:52",
                "3:46",
                "6:22",
                "3:26",
                "5:11",
                "3:44",
                "6:36",
                "3:55",
                "4:17",
                "5:16",
                "5:16",
                "5:16",
                "5:16",
            ],
            "reproducciones":[
                "100.378",
                "97.534",
                "148.004",
                "191.761",
                "1.162.495",
                "170.052",
                "211.733",
                "114.669",
                "260.015",
                "67.935",
                "85.054",
                "69.678",
                "109.875",
                "61.170",
                "2.502.667",
                "2.502.667",
                "2.502.667",
                "2.502.667",
            ]
            
        },
        {
            "artista": "Nightwish",
            "artistaId": "nightwish",
            "disco": "Decades",
            "comment": "Decades es el séptimo álbum recopilatorio de la banda finlandesa Nightwish, salió a la venta el 9 de marzo de 2018 y el mismo día en la banda comenzó la gira Decades: World Tour, la cual cuenta con un DVD en vivo cuya filmación fue en el Estadio Islas Malvinas en Buenos Aires, Argentina, el 30 de septiembre de 2018.",
            "canciones": [
                "The greatest show on Earth",
                "Élan",
                "My Walden",
                "Storytime",
                "I want my tears back",
                "Amaranth",
                "The poet and the pendulum",
                "Nemo",
                "Wish I had an angel",
                "Ghost love score",
                "Slaying the dreamer",
                "End of all hope",
                "10th man down",
                "The kinslayer",
                "Dead boy's poem",
                "Gethsemane",
                "Devil & the deep dark ocean",
                "Sacrament of wilderness",
                "Sleeping sun",
                "Elvenpath",
                "The carpenter",
                "Nightwish"
            ],
            "duraciones": [
                "4:38",
                "5:56",
                "4:36",
                "3:45",
                "5:52",
                "4:52",
                "3:46",
                "6:22",
                "3:26",
                "5:11",
                "3:44",
                "6:36",
                "3:55",
                "4:17",
                "5:16",
                "5:16",
                "5:16",
                "5:16",
                "5:16",
                "5:16",
                "5:16",
                "5:16",
            ],
            "reproducciones":[
                "100.378",
                "97.534",
                "148.004",
                "191.761",
                "1.162.495",
                "170.052",
                "211.733",
                "114.669",
                "260.015",
                "67.935",
                "85.054",
                "69.678",
                "109.875",
                "61.170",
                "2.502.667",
                "2.502.667",
                "2.502.667",
                "2.502.667",
                "2.502.667",
                "2.502.667",
                "2.502.667",
                "2.502.667",
            ]
            
        },
        {
            "artista": "Pantera",
            "artistaId": "pantera",
            "disco": "Essentials",
            "comment": "Pantera fue, sencillamente, una de las bandas de metal más grandes, mejores e influyentes de los años 90. Provenientes de Arlington, Texas, y fundada por el dios de la guitarra Dimebag Darrell y su hermano Vinnie Paul en la batería a principios de los 80. La alineación de la banda se completó con la adición del bajista Rex Brown y el enérgico líder Phil Anselmo, este último transformando el sonido de la banda del glamour de los 80 a una potencia de trash metal. Especialmente los tres primeros álbumes de un sello discográfico importante \"Cowboys From Hell\" (1990), \"Vulgar Display of Power\" (1992) y \"Far Beyond Driven\" (1994) son obras maestras del rock, que vale la pena escucharlas de principio a fin, pero que esta lista de reproducción sea una introducción a, posiblemente, el mejor metal sureño que los años 90 tenían para ofrecer.",
            "canciones": [
                "Walk",
                "Cowboys from hell",
                "Cemetery gates",
                "I'm broken",
                "This love",
                "5 minutes alone",
                "Mouth for war",
                "Domination",
                "Fucking hostile",
                "Becoming",
                "A new lever",
                "Drag the waters",
                "Floods",
                "Rise",
                "Psycho holiday"
            ],
            "duraciones": [
                "4:38",
                "5:56",
                "4:36",
                "3:45",
                "5:52",
                "4:52",
                "3:46",
                "6:22",
                "3:26",
                "5:11",
                "3:44",
                "6:36",
                "3:55",
                "4:17",
                "5:16"
            ],
            "reproducciones":[
                "100.378",
                "97.534",
                "148.004",
                "191.761",
                "1.162.495",
                "170.052",
                "211.733",
                "114.669",
                "260.015",
                "67.935",
                "85.054",
                "69.678",
                "109.875",
                "61.170",
                "2.502.667"
            ]
            
        },
        {
            "artista": "Sonata Artica",
            "artistaId": "sonataArtica",
            "disco": "The Collection",
            "comment": "Sonata Arctica es una banda finlandesa formada en Kemi en 1996 bajo el nombre Tricky Beans, que después cambió a Tricky Means, y finalmente a Sonata Arctica en 1999. Sonata Arctica ha experimentado diversos cambios musicales a lo largo de su carrera, primero con el power metal melódico fusionado con metal neoclásico después adoptando un power con elementos de metal sinfónico hasta el día de hoy. Su cantante Tony Kakko ha comentado influencias de bandas como Stratovarius, Nightwish, Helloween, Scorpions, Iron Maiden, Metallica, Queen, X Japan, entre otras citadas por el grupo en diversas entrevistas.",
            "canciones": [
                "My land",
                "Last drop falls",
                "Wolf & raven",
                "Victoria's secret",
                "Full moon",
                "8th commandment",
                "Don't say a word",
                "Replica",
                "The ruins of my life",
                "The cage",
                "Ain't your fairytale",
                "Kingdom for a heart",
                "Blacksheep",
                "Tallulah",
                "San Sebastin",
                "Unopened",
                "Broken"
            ],
            "duraciones": [
                "4:38",
                "5:56",
                "4:36",
                "3:45",
                "5:52",
                "4:52",
                "3:46",
                "6:22",
                "3:26",
                "5:11",
                "3:44",
                "6:36",
                "3:55",
                "4:17",
                "5:16",
                "3:25",
                "4:43",
            ],
            "reproducciones":[
                "100.378",
                "97.534",
                "148.004",
                "191.761",
                "1.162.495",
                "170.052",
                "211.733",
                "114.669",
                "260.015",
                "67.935",
                "85.054",
                "69.678",
                "109.875",
                "61.170",
                "2.502.667",
                "1.502.667",
                "3.502.667",
            ]
            
        },

    ]
};